- docs/quickstart.md
- examples/app-terraform/main.tf
> Simplify quickstart and examples

- CHANGELOG.md
- docs/quickstart.md
- service/handlers.go
Before:
```sh
ts=2021-08-04T20:15:34.408972Z level=debug txid=11c15f2f-db86-43eb-a715-117ab517a78e message=executing
```
After:
```sh
ts=2021-08-04T20:45:24.138217Z level=debug txid=34f1833d-c2bf-4b84-8dd5-406263125383 op=health-check vault-endpoint=http://127.0.0.1:8200/v1/sys/health message=executing
```
> Fix request logger not logging all key/value pairs.

- CHANGELOG.md
- service/handlers.go
- service/handlers_test.go
- service/testdata/TestCreateProject/fails_to_create_project_when_not_admin_response.json
Prior to this change, it was returning:
```
{"error_message":"error unauthorized, invalid authorization header"}{"token":"vault::"}
```
> Fix invalid json response when creating a project with invalid creds

- .github/workflows/build.yaml
This successfully uploads the coverage report. The [report](https://codecov.io/gh/argoproj-labs/argo-cloudops/commit/0d16b4d78799782dd60b4318897656692fc34fb8/) currently is not processed by codecov as codecov does not have info for the parent commit (base of branch). Once this is merged in, it should create a report for master and future PRs should have coverage reported correctly.
> Add codecov

- docs/quickstart.md
adds a small note to the quickstart so people don't use it in prod
> add a note that quickstart is not configured for prod

- .codecov.yml
Codecov was not being friendly on my other PR, realized we didn't have a config for reasonable threshold or ignoring the files that are ignored by golang test builds.
> chore(ci): controlling codecov with config

- docs/users/envvars.md
- internal/requests/requests.go
- internal/requests/requests_test.go
- internal/validations/validations.go
- internal/validations/validations_test.go
- service/config.go
- service/internal/env/env.go
- service/main.go
This is not a final PR, more of a quick hack / draft for discussion. I didn't cleanly think through naming etc, so poke away.
General concept here (and the same could be applied to git domains) is to enable some enterprise security controls via config. Definitely ran headfirst into the config structure, and specifically the way it (doesn't) flow through. This is a more surgical approach then unwinding some of those bigger issues or moving to a validation struct. Appreciate thoughts on the approach.
> feat(api): adding approved-list for container URIs

- internal/validations/validations.go
- internal/validations/validations_test.go
Stdlib filepath does not support the ** spec, causing the default allow
all to fail on multi-separator URIs.
> fix: corrected bug on default allow-all on approved image uris

- CHANGELOG.md
- argo-cloudops.yaml
- cli/cmd/exec.go
- cli/internal/api/api.go
- cli/internal/api/api_test.go
- cli/internal/api/testdata/exec_request_good.json
- cli/internal/api/testdata/exec_response_good.json
- docs/cli/argo-cloudops.md
- docs/cli/argo-cloudops_exec.md
- docs/developers/api.md
- internal/requests/requests.go
- internal/requests/requests_test.go
- internal/responses/responses.go
- service/handlers.go
resolves #248 
`exec` will use `type` specified in the manifest instead of using the type passed in via the CLI. Leaving `sync` and `diff` CLI flows as is for now to avoid breaking changes. There should be some work in the future to go back and remove both of those flows.
> feat: adding exec command, remove type override

- .golangci.yaml
- internal/requests/requests_test.go
- internal/validations/validations.go
- internal/validations/validations_test.go
- service/handlers.go
> small non breaking rename changes in code/lint config

- cli/internal/api/api_test.go
- cli/internal/api/testdata/execute_workflow_good.json
- docs/developers/api.md
- manifests/cdk_manifest.yaml
- manifests/kube_cdk_manifest.yaml
- manifests/kube_terraform_manifest.yaml
- manifests/terraform_manifest.yaml
- service/testdata/TestCreateWorkflow/can_create_workflow_request.json
- service/testdata/TestCreateWorkflow/fails_to_create_workflow_when_not_admin.json
- service/testdata/TestCreateWorkflow/framework_must_be_valid_request.json
- service/testdata/TestCreateWorkflow/project_must_exist.json
- service/testdata/TestCreateWorkflow/target_must_exist.json
- service/testdata/TestCreateWorkflow/type_must_be_valid_request.json
- workflows/cello-single-step-vault-aws.yaml
Need this pr to be merged before commit shas, quickstart, instructions can be updated/the old workflow can be deleted
> update text strings and copy argo-cloudops workflow to cello

- .goreleaser.yml
- CHANGELOG.md
- Makefile
- cli/cmd/root.go
- docs/cli/cello.md
- docs/cli/cello_diff.md
- docs/cli/cello_exec.md
- docs/cli/cello_get.md
- docs/cli/cello_list.md
- docs/cli/cello_logs.md
- docs/cli/cello_sync.md
- docs/cli/cello_workflow.md
- docs/developers/api.md
- docs/developers/development-env.md
- docs/quickstart.md
- docs/users/cli.md
- mkdocs.yml
- scripts/quickstart_manifest.yaml
- scripts/quickstart_run.sh
- scripts/run_gitops_example.sh
CLI binary has been renamed from argo-cloudops to cello as well as docs referencing the binary commands
> update cli to cello instead of argo cloudops

- service/internal/env/env.go
- service/internal/env/env_test.go
Identifies the ARGO_CLOUDOPS env var prefix as legacy in code, migrates on init, and refactors env tests to: correctly order expected and actual assertions, clarity in naming changes, and coverage for the prefix migration step.
> feat: env prefix migrated to CELLO with legacy fallback

- service/handlers.go
- service/handlers_test.go
- service/test/testdata/TestCreateProject/project_fails_to_create_token_entry.json
- service/test/testdata/TestCreateToken/error_listing_tokens_response.json
- service/test/testdata/TestCreateToken/token_limit_reached_response.json
Limiting the number of tokens created to 2 tokens. This should eventually be configurable in the future.
> feat: limit number of tokens created

- CHANGELOG.md
- service/handlers.go
- service/handlers_test.go
- service/internal/workflow/workflow.go
- service/internal/workflow/workflow_test.go
- service/test/testhelpers/workflowMock.go
I've been seeing the Get Workflows/listWorkflows endpoint return with long response times (~20s with ~4300 workflows). Argo Workflow lib method, [ListWorkflows](https://pkg.go.dev/github.com/argoproj/argo-workflows/v3@v3.3.8/pkg/apiclient/workflow#WorkflowServiceClient), essentially returns the same data as [GetWorkflow](https://pkg.go.dev/github.com/argoproj/argo-workflows/v3@v3.3.8/pkg/apiclient/workflow#WorkflowServiceClient), making the [GetWorkflow/Argo Workflow Status](https://github.com/cello-proj/cello/blob/main/service/handlers.go#L121) call redundant and unnecessarily causing the long response times for the endpoint. Given that ListWorkflows takes ~9s, this change should cut the response time in half.
> Optimize listWorkflows

- cli/internal/api/api.go
- service/config.go
- service/handlers.go
- service/handlers_test.go
- service/internal/git/gitClient.go
As of Go 1.16, `ioutil` has been deprecated. This was causing lint to error during builds.
https://go.dev/doc/go1.16#ioutil
> fix: deprecate ioutil

- CHANGELOG.md
- go.mod
- service/handlers.go
- service/handlers_test.go
- service/internal/workflow/workflow_test.go
Currently, the return is a null for this case. The workflow unit tests were refactored as well, using argo-workflows' mocks based on mockery/testify.
> fix: return an empty array for List workflows for targets with no workflows

- go.mod
- service/internal/workflow/workflow.go
An EOF was being returned when streaming workflow logs on large outputs, and the stream was taking much longer than expected when compared to `argo logs` cli command. Looking into this deeper, Cello's implementation of log streaming made a Argo Workflow status call for each log line. This was the cause of log streaming not coming in fast enough. Theory is that the EOF was being returned because Cello was streaming a log that no longer existed in Argo Workflow.
> fix(logs): remove workflow status call from cello log stream

- service/handlers.go
- service/handlers_test.go
Closes #148 
This PR changes the `Content-Type` header for healthcheck resonses to be a `text/plain` content type rather than an `application/json` content type.
> [148] - Healthcheck endpoint returns application/json content type

- service/handlers.go
- service/internal/workflow/workflow.go
- service/internal/workflow/workflow_test.go
Add an operation type (bootstrap/sync) to argo workflow so the workflow can know what it is running and decide what steps can be triggered.
> add type to workflow parameter
